"""Added created_by_user to Product

Revision ID: 80af069a5c97
Revises: a2ef8c144b81
Create Date: 2025-02-12 10:33:34.699328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80af069a5c97'
down_revision = 'a2ef8c144b81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_user', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('created_by_user')

    # ### end Alembic commands ###
